routes/web.php
<?php

use App\Http\Controllers\KaryawanController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // CRUD Karyawan
    Route::prefix('karyawan')->group(function () {
        Route::get('/', [KaryawanController::class, 'index'])->name('karyawan.index');
        Route::get('/create', [KaryawanController::class, 'create'])->name('karyawan.create');
        Route::post('/store', [KaryawanController::class, 'store'])->name('karyawan.store');
        Route::get('/show/{id}', [KaryawanController::class, 'show'])->name('karyawan.show');
        Route::get('/edit/{id}', [KaryawanController::class, 'edit'])->name('karyawan.edit');
        Route::put('/update/{id}', [KaryawanController::class, 'update'])->name('karyawan.update');
        Route::delete('/destroy/{id}', [KaryawanController::class, 'destroy'])->name('karyawan.destroy');
    });
});

require __DIR__.'/auth.php';

app/Models/Karyawan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;

class Karyawan extends Model
{
    use HasFactory, SoftDeletes;
    protected $fillable = [
        'name',
        'tanggal_lahir',
        'alamat',
        'photo_url',
        'status'
    ];
}

app/Http/Controllers/KaryawanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\KaryawanRequest;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;
use App\Repositories\Interfaces\KaryawanRepositoryInterface;

class KaryawanController extends Controller
{
    private $karyawanRepository;

    public function __construct(KaryawanRepositoryInterface $karyawanRepository)
    {
        $this->karyawanRepository = $karyawanRepository;
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return $this->karyawanRepository->allKaryawans();
        }

        return view('pages.karyawan.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pages.karyawan.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(KaryawanRequest $request)
    {
        $data = $request->all();
        if ($request->hasFile('photo_url')) {
            $path = $request->file('photo_url')->store('public/image');
            $filename = Storage::url($path);

            $data['photo_url'] = $filename;
        }
        $this->karyawanRepository->storeKaryawan($data);

        return redirect()->route('karyawan.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $karyawan = $this->karyawanRepository->findKaryawan($id);
        $umur = Carbon::parse($karyawan->tanggal_lahir)->diff(Carbon::now())->format('%y Tahun');

        return view('pages.karyawan.show', compact([
            'karyawan', 
            'umur'
        ]));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $karyawan = $this->karyawanRepository->findKaryawan($id);

        return view('pages.karyawan.edit', compact('karyawan'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(KaryawanRequest $request, string $id)
    {
        if($request->hasFile('photo_url')) {
            $path = $request->file('photo_url')->store('public/image');
            $filename = Storage::url($path);

            if($request->old_url) {
                Storage::delete(str_replace('/storage', '/public', $request->old_url));
            }
        } else {
            $filename = $request->old_url;
        }

        if(!isset($data['status'])) {
            $data['status'] = 0;
        }

        $data = $request->except(['photo_url', 'old_url']);
        $data['photo_url'] = $filename;
        $this->karyawanRepository->updateKaryawan($data, $id);

        return redirect()->route('karyawan.index')->with('message, Data Berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $this->karyawanRepository->destroyKaryawan($id);

        return redirect()->route('karyawan.index')->with('status', 'Data Berhasil dihapus');
    }
}

app/View/Components/TemplateLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class TemplateLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.template');
    }
}

resources/views/pages/karyawan/create.blade.php
<x-template-layout>
    <x-slot name="header">
        {{ __('Karyawans') }}
    </x-slot>

    <div class="container-fluid">
        <div class="card mb-4">
            <div class="card-header">
                <h3>Tambah Karyawan</h3>
            </div>
            <form action="{{ route('karyawan.store') }}" method="POST" enctype="multipart/form-data">
                <div class="card-body">
                    @csrf
                    <div>
                        <x-input-label for="karyawan_id"  :value="__('Karyawan')" />
                        <x-text-input id="name" name="name" type="text" class="mt-1 block w-full"
                            :value="old('name')" />
                        <x-input-error class="mt-2" :messages="$errors->get('name')" />
                    </div>
                    <div>
                        <x-input-label for="tanggal_lahir" :value="__('Tanggal Lahir')" />
                        <x-text-input id="tanggal_lahir" name="tanggal_lahir" type="date" class="mt-1 block w-full"
                            :value="old('tanggal_lahir')" />
                        <x-input-error class="mt-2" :messages="$errors->get('tanggal_lahir')" />
                    </div>
                    <div>
                        <x-input-label for="alamat" :value="__('Alamat')" />
                        <x-text-input id="alamat" name="alamat" type="text" class="mt-1 block w-full"
                            :value="old('alamat')" />
                        <x-input-error class="mt-2" :messages="$errors->get('alamat')" />
                    </div>
                    <div>
                        <x-input-label for="photo_url" :value="__('Upload Gambar')" />
                        <x-text-input id="photo_url" name="photo_url" type="file" class="mt-1 block w-full"
                            :value="old('photo_url')" />
                        <x-input-error class="mt-2" :messages="$errors->get('photo_url')" />
                    </div>
                    <div>
                        <x-input-label for="status" :value="__('Sudah Menikah ?')" />
                        <x-text-input id="status" name="status" type="checkbox" class="mt-1 block w-full mb-2"
                            :value="1"/>
                        <x-input-error class="mt-2" :messages="$errors->get('status')" />
                    </div>
                </div>
                <div class="card-footer">
                    <button class="btn btn-success">
                        Simpan
                    </button>
                </div>
            </form>
        </div>
    </div>
</x-template-layout>

resources/views/pages/karyawan/edit.blade.php
<x-template-layout>
    <x-slot name="header">
        {{ __('Karyawans') }}
    </x-slot>

    <div class="container-fluid">
        <div class="card mb-4">
            <div class="card-header">
                <h3>Edit Karyawan</h3>
            </div>
            <form action="{{ route('karyawan.update', $karyawan->id) }}" method="POST" enctype="multipart/form-data">
                <div class="card-body">
                    @csrf
                    @method('PUT')
                    <div>
                        <x-input-label for="karyawan_id" :value="__('Karyawan')" />
                        <x-text-input id="name" name="name" type="text" class="mt-1 block w-full"
                            :value="old('name', $karyawan->name)" />
                        <x-input-error class="mt-2" :messages="$errors->get('name')" />
                    </div>
                    <div>
                        <x-input-label for="tanggal_lahir" :value="__('Tanggal Lahir')" />
                        <x-text-input id="tanggal_lahir" name="tanggal_lahir" type="date" class="mt-1 block w-full"
                            :value="old('tanggal_lahir', $karyawan->tanggal_lahir)" />
                        <x-input-error class="mt-2" :messages="$errors->get('tanggal_lahir')" />
                    </div>
                    <div>
                        <x-input-label for="alamat" :value="__('Alamat')" />
                        <x-text-input id="alamat" name="alamat" type="text" class="mt-1 block w-full"
                            :value="old('alamat', $karyawan->alamat)" />
                        <x-input-error class="mt-2" :messages="$errors->get('alamat')" />
                    </div>
                    <div>
                        <x-input-label for="photo_url" :value="__('Ganti Gambar')" />
                        <x-text-input id="photo_url" name="photo_url" type="file" class="mt-1 block w-full"
                            :value="old('photo_url')" />
                        <x-input-error class="mt-2" :messages="$errors->get('photo_url')" />
                    </div>
                    <div>
                        <input name="old_url" type="hidden" value="{{ old('photo',$karyawan->photo_url) }}">
                        <div class="card mt-2 mb-4">
                            <div class="card-header d-flex justify-content-center">
                                <img src="{{ $karyawan->photo_url }}" class="card-image-top img-fluid mr-4"
                                    style="height: 10rem;" alt="{{ $karyawan->photo_url }}">
                            </div>
                        </div>
                    </div>
                    <div>
                        <x-input-label for="status" :value="__('Sudah Menikah ?')" />
                        <x-text-input type="hidden" name="status" :value="0" />
                        <input type="checkbox" id="status" name="status" value="1" {{ old('status', $karyawan->status) ? 'checked' : '' }} class="mt-1 block w-full mb-2 form-control">
                        <x-input-error class="mt-2" :messages="$errors->get('status')" />
                    </div>
                </div>
                <div class="card-footer">
                    <button class="btn btn-success">
                        Simpan
                    </button>
                </div>
            </form>
        </div>
    </div>
</x-template-layout>

resources/views/pages/karyawan/index.blade.php
<x-template-layout>
    <x-slot name="header">
        {{ __('Karyawans') }}
    </x-slot>

    <div class="container-fluid">
        <div class="card mb-4 shadow-lg">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h3>List Karyawan</h3>
                <a href="{{ route('karyawan.create') }}" class="btn btn-success">
                    +
                </a>
            </div>
            <div class="card-body">
                <table id="karyawanTable" class="table table-hover text-center">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Nama Karyawan</th>
                            <th>Tanggal Lahir</th>
                            <th>Alamat</th>
                            <th>Photo</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody><tbody>
                </table>
            </div>
        </div>
    </div>

    <x-slot name="script">
        <script>
            $(document).ready(function() {
                var datatable = $('#karyawanTable').DataTable({
                    ajax: {
                        url: '{!! url()->current() !!}'
                    },
                    columns: [
                        { data: 'id', name: 'id', width: '5%' },
                        { data: 'name', name: 'name' },
                        { data: 'tanggal_lahir', name: 'tanggal_lahir' },
                        { data: 'alamat', name: 'alamat' },
                        { 
                            data: 'photo_url', 
                            name: 'photo_url',
                            render: function(data, type, row) {
                                var defaultImage = '{{ asset('template/img/sql-server.jpg') }}';
                                var imageUrl = data ? data :defaultImage;
                                return '<img src="' + imageUrl + '" alt="photo" style="width: 80px;" class="shadow-lg">';
                            } 
                        },
                        { data: 'status', name: 'status' },
                        {
                            data: 'action',
                            name: 'action',
                            orderable: false,
                            searchable: true,
                            width: '25%'
                        }
                    ]
                });
            })
        </script>
    </x-slot>
    
</x-template-layout>

resources/views/pages/karyawan/show.blade.php
<x-template-layout>
    <x-slot name="header">
        {{ __('Detail Karyawan') }}
    </x-slot>
    <div class="container-fluid d-flex justify-content-center mb-4">
        <div class="card shadow-lg border-left-warning" style="width: 25rem;">
            <div class="card-header">
                Card Information Karyawan {{ $karyawan->id }}
            </div>
            <img src="{{ $karyawan->photo_url }}" class="card-image-top" style="height: 20rem;"
                alt="{{ $karyawan->photo_url }}">
            <div class="card-body">
                <h5 class="card-title shadow p-2 text-dark text-center"><b>{{ $karyawan->name }}</b></h5>
                <table class="table">
                    <tr>
                        <th>Tanggal Lahir</th>
                        <td>:</td>
                        <td>{{ $karyawan->tanggal_lahir }}</td>
                    </tr>
                    <tr>
                        <th>Umur</th>
                        <td>:</td>
                        <td>{{ $umur }}</td>
                    </tr>
                    <tr>
                        <th>Alamat</th>
                        <td>:</td>
                        <td>{{ $karyawan->alamat }}</td>
                    </tr>
                    <tr>
                        <th>Status Pernikahan</th>
                        <td>:</td>
                        <td>{{ $karyawan->status ? 'Menikah' : 'Lajang' }} </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</x-template-layout>